// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSecretsService is an autogenerated mock type for the Service type
type MockSecretsService struct {
	mock.Mock
}

type MockSecretsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretsService) EXPECT() *MockSecretsService_Expecter {
	return &MockSecretsService_Expecter{mock: &_m.Mock}
}

// GetSecretValue provides a mock function with given fields: secretName
func (_m *MockSecretsService) GetSecretValue(secretName string) (string, error) {
	ret := _m.Called(secretName)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretValue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(secretName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(secretName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(secretName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretsService_GetSecretValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretValue'
type MockSecretsService_GetSecretValue_Call struct {
	*mock.Call
}

// GetSecretValue is a helper method to define mock.On call
//   - secretName string
func (_e *MockSecretsService_Expecter) GetSecretValue(secretName interface{}) *MockSecretsService_GetSecretValue_Call {
	return &MockSecretsService_GetSecretValue_Call{Call: _e.mock.On("GetSecretValue", secretName)}
}

func (_c *MockSecretsService_GetSecretValue_Call) Run(run func(secretName string)) *MockSecretsService_GetSecretValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSecretsService_GetSecretValue_Call) Return(_a0 string, _a1 error) *MockSecretsService_GetSecretValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretsService_GetSecretValue_Call) RunAndReturn(run func(string) (string, error)) *MockSecretsService_GetSecretValue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretsService creates a new instance of MockSecretsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretsService {
	mock := &MockSecretsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
