// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	SystemCreatedAt time.Time
	SystemUpdatedAt time.Time
	Status          string
}

type OrderItem struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	OrderID         uuid.UUID
	ProductID       uuid.UUID
	SystemCreatedAt time.Time
	Quantity        int32
	PriceCents      int32
}

type Organization struct {
	ID              uuid.UUID
	SystemCreatedAt time.Time
	SystemUpdatedAt time.Time
	Name            string
	Slug            string
}

type Product struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	SystemCreatedAt time.Time
	SystemUpdatedAt time.Time
	Name            string
	Category        string
	PriceCents      int32
}
