// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeOrder = `-- name: CloseOrder :one
UPDATE app_sweetshop.orders
SET system_updated_at = $2, status = 'closed'
WHERE id = $1
RETURNING id, organization_id, system_created_at, system_updated_at, status
`

type CloseOrderParams struct {
	ID              uuid.UUID
	SystemUpdatedAt time.Time
}

func (q *Queries) CloseOrder(ctx context.Context, arg CloseOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, closeOrder, arg.ID, arg.SystemUpdatedAt)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SystemCreatedAt,
		&i.SystemUpdatedAt,
		&i.Status,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO app_sweetshop.orders (id, organization_id, system_created_at, system_updated_at, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderParams struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	SystemCreatedAt time.Time
	SystemUpdatedAt time.Time
	Status          string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.ID,
		arg.OrganizationID,
		arg.SystemCreatedAt,
		arg.SystemUpdatedAt,
		arg.Status,
	)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO app_sweetshop.order_items (id, organization_id, order_id, product_id, system_created_at, quantity, price_cents)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOrderItemParams struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	OrderID         uuid.UUID
	ProductID       uuid.UUID
	SystemCreatedAt time.Time
	Quantity        int32
	PriceCents      int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.ID,
		arg.OrganizationID,
		arg.OrderID,
		arg.ProductID,
		arg.SystemCreatedAt,
		arg.Quantity,
		arg.PriceCents,
	)
	return err
}

const findOrderByID = `-- name: FindOrderByID :one
SELECT id, organization_id, system_created_at, system_updated_at, status FROM app_sweetshop.orders WHERE id = $1
`

func (q *Queries) FindOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, findOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SystemCreatedAt,
		&i.SystemUpdatedAt,
		&i.Status,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, organization_id, order_id, product_id, system_created_at, quantity, price_cents FROM app_sweetshop.order_items WHERE order_id = $1 ORDER BY system_created_at
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrderID,
			&i.ProductID,
			&i.SystemCreatedAt,
			&i.Quantity,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
