// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO app_sweetshop.organizations (id, system_created_at, system_updated_at, name, slug)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrganizationParams struct {
	ID              uuid.UUID
	SystemCreatedAt time.Time
	SystemUpdatedAt time.Time
	Name            string
	Slug            string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.Exec(ctx, createOrganization,
		arg.ID,
		arg.SystemCreatedAt,
		arg.SystemUpdatedAt,
		arg.Name,
		arg.Slug,
	)
	return err
}

const findOrganizationByID = `-- name: FindOrganizationByID :one
SELECT id, system_created_at, system_updated_at, name, slug FROM app_sweetshop.organizations WHERE id = $1
`

func (q *Queries) FindOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, findOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.SystemCreatedAt,
		&i.SystemUpdatedAt,
		&i.Name,
		&i.Slug,
	)
	return i, err
}

const findOrganizationBySlug = `-- name: FindOrganizationBySlug :one
SELECT id, system_created_at, system_updated_at, name, slug FROM app_sweetshop.organizations WHERE slug = $1
`

func (q *Queries) FindOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, findOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.SystemCreatedAt,
		&i.SystemUpdatedAt,
		&i.Name,
		&i.Slug,
	)
	return i, err
}
