// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CloseOrder(ctx context.Context, arg CloseOrderParams) (Order, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	DeleteProduct(ctx context.Context, id uuid.UUID) (int64, error)
	FindOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	FindOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	FindOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	FindProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
